In [25]:
import numpy as np

In [26]:
N=10000000
x=np.random.random((N,))*2
y=np.random.random((N,))*2

In [27]:
x

array([ 0.54135227,  0.63045838,  1.50586266, ...,  0.35131807,
        1.1186041 ,  1.11463075])

In [28]:
y

array([ 0.34989585,  0.81752643,  0.55682288, ...,  0.57863789,
        1.22768564,  0.59292667])

In [29]:
np.var(x*y)

0.77712712652734395

In [30]:
7/9

0.7777777777777778

In [31]:
b=(x*y>=1);b

array([False, False, False, ..., False,  True, False], dtype=bool)

In [32]:
np.sum(b)/N

0.40333989999999997